services:
  server:
    build:
      context: ./server
      dockerfile: Dockerfile
    container_name: snapdash-server
    ports:
      - "3001:3001"
    depends_on:
      - db
      - seaweedfs
    env_file: ./server/.env
    stop_grace_period: 10s

  admin:
    build:
      context: ./admin
      dockerfile: Dockerfile
    container_name: snapdash-admin
    ports:
      - "3000:80"
    depends_on:
      - server

  db:
    image: docker.io/postgres:18.0-alpine3.22
    environment:
      POSTGRES_PASSWORD: tvn5p45n
      POSTGRES_DB: snapdash
    healthcheck:
      test:
        [
          "CMD",
          "pg_isready",
          "-d",
          "snapdash",
          "-U",
          "postgres"
        ]
      interval: 10s
      timeout: 5s
      retries: 5
    restart: on-failure
    volumes:
      - db-data:/var/lib/postgresql/data

  adminer:
    image: docker.io/adminer
    restart: always
    ports:
      - 8080:8080

  seaweedfs:
    image: docker.io/chrislusf/seaweedfs:latest
    container_name: snapdash-seaweedfs
    ports:
      - "8333:8333"  # S3 API
      - "9333:9333"  # Master server
      - "8888:8888"  # Filer
    command: "server -s3 -dir=/data -s3.config=/etc/seaweedfs/s3.json"
    volumes:
      - seaweedfs-data:/data
      - ./seaweedfs-config:/etc/seaweedfs
    healthcheck:
      test: ["CMD", "wget", "-q", "--spider", "http://localhost:9333/cluster/status"]
      interval: 10s
      timeout: 5s
      retries: 5
    restart: on-failure



volumes:
  db-data:
  seaweedfs-data:
